from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^config.(?P<fmt>(xml|json|html|txt))$', views.rest, {'GET': views.read_config, 'POST': views.create_config}),
    (r'^item.(?P<fmt>(xml|json|html|txt))$', views.rest, {'GET': views.read_item_list, 'POST': views.create_item}),
    (r'^item/(?P<iid>\d+)$', views.rest, {'GET': views.read_item_data, 'PUT': views.update_item_data}),
    (r'^item/(?P<iid>\d+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_item, 'GET': views.read_item}),
    (r'^item/(?P<iid>\d+)/(?P<cid>\d+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_comment, 'GET': views.read_comment}),
    (r'^item/(?P<iid>\d+)/(?P<cid>\d+)/key.(?P<fmt>(xml|json|html|txt))$', views.rest, {'POST': views.create_comment_key}),
    (r'^item/(?P<iid>\d+)/(?P<cid>\d+)/key/(?P<key>\w+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_comment_key, 'GET': views.read_comment_key, 'PUT': views.update_comment_key}),
    (r'^item/(?P<iid>\d+)/clone.(?P<fmt>(xml|json|html|txt))$', views.rest, {'GET': views.read_clone_list, 'POST': views.create_clone}),
    (r'^item/(?P<iid>\d+)/comment.(?P<fmt>(xml|json|html|txt))$', views.rest, {'GET': views.read_comment_list, 'POST': views.create_comment}),
    (r'^item/(?P<iid>\d+)/key.(?P<fmt>(xml|json|html|txt))$', views.rest, {'POST': views.create_item_key}),
    (r'^item/(?P<iid>\d+)/key/(?P<key>\w+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_item_key, 'GET': views.read_item_key, 'PUT': views.update_item_key}),
    (r'^relation.(?P<fmt>(xml|json|html|txt))$', views.rest, {'GET': views.read_relation_list, 'POST': views.create_relation}),
    (r'^relation/(?P<rid>\d+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_relation, 'GET': views.read_relation}),
    (r'^relation/(?P<rid>\d+)/key.(?P<fmt>(xml|json|html|txt))$', views.rest, {'POST': views.create_relation_key}),
    (r'^relation/(?P<rid>\d+)/key/(?P<key>\w+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_relation_key, 'GET': views.read_relation_key, 'PUT': views.update_relation_key}),
    (r'^tag.(?P<fmt>(xml|json|html|txt))$', views.rest, {'GET': views.read_tag_list, 'POST': views.create_tag}),
    (r'^tag/(?P<tid>\d+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_tag, 'GET': views.read_tag}),
    (r'^tag/(?P<tid>\d+)/key.(?P<fmt>(xml|json|html|txt))$', views.rest, {'POST': views.create_tag_key}),
    (r'^tag/(?P<tid>\d+)/key/(?P<key>\w+).(?P<fmt>(xml|json|html|txt))$', views.rest, {'DELETE': views.delete_tag_key, 'GET': views.read_tag_key, 'PUT': views.update_tag_key}),
    (r'^version.(?P<fmt>(xml|json|html|txt))$', views.rest, {'GET': views.read_version}),
)
