from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^ui/create-comment/(?P<iid>\d+).html$', views.rest, {'GET': views.read_create_comment}),
    (r'^ui/create-item.html$', views.rest, {'GET': views.read_create_item}),
    (r'^ui/create-relation.html$', views.rest, {'GET': views.read_create_relation}),
    (r'^ui/create-tag.html$', views.rest, {'GET': views.read_create_tag}),
    (r'^ui/data/(?P<iid>\d+)$', views.rest, {'GET': views.read_data/IID}),
    (r'^ui/delete-comment/(?P<iid>\d+)/(?P<cid>\d+).html$', views.rest, {'GET': views.read_delete_comment}),
    (r'^ui/delete-item/(?P<iid>\d+).html$', views.rest, {'GET': views.read_delete_item}),
    (r'^ui/delete-relation/(?P<rid>\d+).html$', views.rest, {'GET': views.read_delete_relation}),
    (r'^ui/delete-tag/(?P<tid>\d+).html$', views.rest, {'GET': views.read_delete_tag}),
    (r'^ui/list-comments/(?P<iid>\d+).html$', views.rest, {'GET': views.read_list_comments}),
    (r'^ui/list-items.html$', views.rest, {'GET': views.read_list_items}),
    (r'^ui/list-relations.html$', views.rest, {'GET': views.read_list_relations}),
    (r'^ui/list-tags.html$', views.rest, {'GET': views.read_list_tags}),
    (r'^ui/read-comment/(?P<iid>\d+)/(?P<cid>\d+).html$', views.rest, {'GET': views.read_read_comment}),
    (r'^ui/read-config.html$', views.rest, {'GET': views.read_read_config}),
    (r'^ui/read-item/(?P<iid>\d+).html$', views.rest, {'GET': views.read_read_item}),
    (r'^ui/read-relation/(?P<rid>\d+).html$', views.rest, {'GET': views.read_read_relation}),
    (r'^ui/read-tag/(?P<tid>\d+).html$', views.rest, {'GET': views.read_read_tag}),
    (r'^ui/update-comment/(?P<iid>\d+)/(?P<cid>\d+).html$', views.rest, {'GET': views.read_update_comment}),
    (r'^ui/update-config.html$', views.rest, {'GET': views.read_update_config}),
    (r'^ui/update-item/(?P<iid>\d+).html$', views.rest, {'GET': views.read_update_item}),
    (r'^ui/update-relation/(?P<rid>\d+).html$', views.rest, {'GET': views.read_update_relation}),
    (r'^ui/update-tag/(?P<tid>\d+).html$', views.rest, {'GET': views.read_update_tag}),
    (r'^ui/version.html$', views.rest, {'GET': views.read_version.html}),
)
